version: "3"

services:

  mongo-entrega:
    image: mongo
    container_name: "mongo-entrega"
    command: mongod --port 27017
    ports:
      - 27021:27017

  mongo-pedido:
    image: mongo
    container_name: "mongo-pedido"
    command: mongod --port 27017
    ports:
      - "27020:27017" 

  pedido:
    container_name: "pedidoService"
    build:
      context: ./PedidoService
      dockerfile: Dockerfile
    environment:
      PORT: 8000
      RABBIT: "rabbitmq"
      DB_PORT: 27017
      DB_NAME: pedido
      DB_HOST: "mongo-pedido"
      PEDIDO_HOST: "pedidoService"
      PEDIDO_PORT: 8000
      ENTREGA_HOST: "entregaService"
      ENTREGA_PORT: 8000
    links:
      - mongo-pedido
      - rabbitmq
    depends_on:
      - mongo-pedido
      - rabbitmq
    ports:
      - 8001:8000

  entrega:
    container_name: "entregaService"
    build:
      context: ./EntregaService
    environment:
      PORT: 8000
      RABBIT: "rabbitmq"
      DB_PORT: 27017
      DB_NAME: entrega
      DB_HOST: "mongo-entrega"
      PEDIDO_HOST: "pedidoService"
      PEDIDO_PORT: 8000
      ENTREGA_HOST: "entregaService"
      ENTREGA_PORT: 8000
    links:
      - mongo-entrega
      - rabbitmq
    depends_on:
      - mongo-entrega
      - rabbitmq
    ports:
      - 8002:8000

  rabbitmq:
    image: rabbitmq
    container_name: "rabbitmq"
    ports:
      - 5673:5672
      - 15673:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672/api/"]
      interval: 30s
      timeout: 10s
      retries: 5
