version: "3"

services:

  rabbitmq:
    image: rabbitmq
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app-network
  
  mongo-entrega:
    image: mongo
    container_name: "mongo-entrega"
    command: mongod --port 27017
    ports:
      - 27021:27017
    networks:
      - app-network  

  mongo-pedido:
    image: mongo
    container_name: "mongo-pedido"
    command: mongod --port 27017
    ports:
      - "27020:27017" 
    networks:
      - app-network
  
  pedido:
    container_name: "pedidoService"
    build:
      context: ./PedidoService
      dockerfile: Dockerfile
    environment:
      PORT: 8000
      RABBIT: "rabbitmq"
      DB_PORT: 27017
      DB_NAME: pedido
      DB_HOST: "mongo-pedido"
      ENTREGA_HOST: "entregaService"
      ENTREGA_PORT: 8000
    links:
      - mongo-pedido
      - rabbitmq
    depends_on:
      - mongo-pedido
      - rabbitmq
    ports:
      - 8001:8000
    networks:
      - app-network
  
  entrega:
    container_name: "entregaService"
    build:
      context: ./EntregaService
    environment:
      PORT: 8000
      RABBIT: "rabbitmq"
      DB_PORT: 27017
      DB_NAME: entrega
      DB_HOST: "mongo-entrega"
      PEDIDO_HOST: "pedidoService"
      PEDIDO_PORT: 8000
    links:
      - mongo-entrega
      - rabbitmq
    depends_on:
      - mongo-entrega
      - rabbitmq
    ports:
      - 8002:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge